sdo/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from organization.forms import *
from django.contrib import admin
from organization.views import MaterialListView, MaterialView, TestListView, TestView, StatListView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'organization.views.home', name='home'),

    url(r'^test/$', TestListView.as_view(), name='test'),
	
    url(r'^test/university/(?P<university_id>\d+)/$', TestListView.as_view(), name='test_university'),
    url(r'^test/university/(?P<university_id>\d+)/department/(?P<department_id>\d+)/$', TestListView.as_view(), name='test_department'),
    url(r'^test/university/(?P<university_id>\d+)/department/(?P<department_id>\d+)/subject/(?P<subject_id>\d+)/$', TestListView.as_view(), name='test_subject'),
    url(r'^test/university/(?P<university_id>\d+)/department/(?P<department_id>\d+)/subject/(?P<subject_id>\d+)/lector/(?P<lector_id>\d+)/$', TestListView.as_view(), name='test_lector'),
    url(r'^test/university/(?P<university_id>\d+)/department/(?P<department_id>\d+)/subject/(?P<subject_id>\d+)/lector/(?P<lector_id>\d+)/(?P<test_id>\d+)/$', TestView.as_view(), name='test_view'),
# добавление новго теста
    url(r'^add_education_test/$', 'organization.views.add_education_test', name='add_education_test'),
# редактирование вопроса к тесту
    url(r'^test/(?P<test_id>\d+)/question/(?P<question_id>\d+)/$', 'organization.views.question_view', name='question_view'),
# удаление вопроса из теста
    url(r'^remove_test_question/(?P<question_id>\d+)/$', 'organization.views.remove_test_question', name='remove_test_question'),
# публикация вопроса в тесте
    url(r'^toggle_pub_test_question/(?P<question_id>\d+)/$', 'organization.views.toggle_pub_test_question', name='toggle_pub_test_question'),
# публикация теста
    url(r'^toggle_pub_education_test/(?P<test_id>\d+)/$', 'organization.views.toggle_pub_education_test', name='toggle_pub_education_test'),
	url(r'^add_education_discipline/(?P<discipline_id>\d+)/$', TestListView.as_view(), name='test'),


    # прохождение теста
# запрос на инициализацию теста
    url(r'^ajax/init_test/$', 'organization.views.init_test', name='init_test'),
# запрос на получение следующего вопроса
    url(r'^ajax/get_next_question/$', 'organization.views.get_next_question', name='get_next_question'),
# сохранение ответа на вопрос
    url(r'^ajax/save_question/$', 'organization.views.save_question', name='save_question'),
# аварийное завершение теста
    url(r'^ajax/force_finish_test/$', 'organization.views.force_finish_test', name='force_finish_test'),


# запрос на получение нового id сессии для прохождения теста
    url(r'^ajax/get_new_uuid/$', 'organization.views.get_new_uuid', name='get_new_uuid'),




    url(r'^material/$', MaterialListView.as_view(), name='material'),
    url(r'^material/university/(?P<university_id>\d+)/$', MaterialListView.as_view(), name='material_university'),
    url(r'^material/university/(?P<university_id>\d+)/department/(?P<department_id>\d+)/$', MaterialListView.as_view(), name='material_department'),
    url(r'^material/university/(?P<university_id>\d+)/department/(?P<department_id>\d+)/subject/(?P<subject_id>\d+)/$', MaterialListView.as_view(), name='material_subject'),
    url(r'^material/university/(?P<university_id>\d+)/department/(?P<department_id>\d+)/subject/(?P<subject_id>\d+)/lector/(?P<lector_id>\d+)/$', MaterialListView.as_view(), name='material_lector'),
    url(r'^material/university/(?P<university_id>\d+)/department/(?P<department_id>\d+)/subject/(?P<subject_id>\d+)/lector/(?P<lector_id>\d+)/(?P<material_id>\d+)/$', MaterialView.as_view(), name='material_view'),


    url(r'^stat/$', StatListView.as_view(), name='stat'),
    url(r'^stat/university/(?P<university_id>\d+)/$', StatListView.as_view(), name='stat_university'),
    url(r'^stat/university/(?P<university_id>\d+)/department/(?P<department_id>\d+)/$', StatListView.as_view(), name='stat_department'),
    url(r'^stat/university/(?P<university_id>\d+)/department/(?P<department_id>\d+)/subject/(?P<subject_id>\d+)/$', StatListView.as_view(), name='stat_subject'),
    url(r'^stat/university/(?P<university_id>\d+)/department/(?P<department_id>\d+)/subject/(?P<subject_id>\d+)/lector/(?P<lector_id>\d+)/$', StatListView.as_view(), name='stat_lector'),


# добавление новго учебного материала
    url(r'^add_education_material/$', 'organization.views.add_education_material', name='add_education_material'),
# включение/выключени публикации материала
    url(r'^toggle_pub_education_material/(?P<material_id>\d+)/$', 'organization.views.toggle_pub_education_material', name='toggle_pub_education_material'),
# удаление материала вместе со всеми файлами
    url(r'^remove_education_material/(?P<material_id>\d+)/$', 'organization.views.remove_education_material', name='remove_education_material'),
# удаление файла в учебном материале
    url(r'^remove_education_material_file/(?P<file_id>\d+)/$', 'organization.views.remove_education_material_file', name='remove_education_material_file'),

# для меню
    url(r'^ajax/get_university_list/$', 'organization.views.get_university_list', name='get_university_list'),
    url(r'^ajax/get_department_list/$', 'organization.views.get_department_list', name='get_department_list'),
    url(r'^ajax/get_subject_list/$', 'organization.views.get_subject_list', name='get_subject_list'),
    url(r'^ajax/get_lector_list/$', 'organization.views.get_lector_list', name='get_lector_list'),



    url(r'^accounts/registration/$', 'organization.registration.registration', name='registration'),
    url(r'^accounts/registration/success/$', 'organization.registration.registration_success', name='registration_success'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'authentication_form': UserAuthenticationForm}, name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^accounts/password_reset/$', 'django.contrib.auth.views.password_reset', {'post_reset_redirect':'/accounts/password_reset_done/', 'password_reset_form':UserPasswordResetForm}, name='password_reset'),
    url(r'^accounts/password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^accounts/password_reset_done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^accounts/password_reset_complete/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

    url(r'^admin/', include(admin.site.urls)),

)
urlpatterns += patterns('',
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    # url(r'^ckeditor/', include('ckeditor.urls')),
    (r'^ckeditor/', include('ckeditor.urls')),
)

organization/models.py
# -*- coding: utf-8 -*-
import os
from django.db import models
from django.contrib.auth.models import User, Group
from django.dispatch import receiver
from ckeditor.fields import RichTextField
from django.conf import settings
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

class University(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название ВУЗа')
    full_name = models.CharField(max_length=255, verbose_name='Полное название ВУЗа')

    class Meta:
        verbose_name = 'ВУЗ'
        verbose_name_plural = 'ВУЗы'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return 'university/%s/' % self.pk


class Department(models.Model):
    university = models.ForeignKey(University, verbose_name='ВУЗ')
    name = models.CharField(max_length=255, verbose_name='Название кафедры')
    full_name = models.CharField(max_length=255, verbose_name='Полное название кафедры')

    class Meta:
        verbose_name = 'Кафедра'
        verbose_name_plural = 'Кафедры'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return 'department/%s/' % self.pk


class Subject(models.Model):
    department = models.ForeignKey(Department, verbose_name='Кафедра')
    name = models.CharField(max_length=255, verbose_name='Название дисциплины')
    full_name = models.CharField(max_length=255, verbose_name='Полное название дисциплины')

    class Meta:
        verbose_name = 'Дисциплина'
        verbose_name_plural = 'Дисциплины'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return 'subject/%s/' % self.pk


class UserProfile(models.Model):
    # пользователя ни чем не ограничиваем может смотреть все за исключением преподов, которые видят только свои материалы
    user = models.OneToOneField(User,related_name="profile")
    university = models.ForeignKey(University, verbose_name='ВУЗ', null=True) # основной вуз
    department = models.ForeignKey(Department, verbose_name='Кафедра', null=True) # основная кафедра
    status = models.ForeignKey(Group, verbose_name='Статус пользователя', null=True) #Статус теперь привязан к основной группе
    middle_name = models.CharField(max_length=255, verbose_name='Отчество', blank=True)

    def create_profile(sender, **kwargs):
        if kwargs['created']:
            UserProfile.objects.create(user=kwargs['instance'])
    models.signals.post_save.connect(create_profile, sender=User)

    def get_full_name(self):
        full_name = '%s %s' % (self.user.last_name, self.user.first_name)
        if self.middle_name:
            full_name += ' %s' % self.middle_name
        return full_name

    def get_name(self):
        print self.user.first_name[:1]
        name = '%s %s.' % (self.user.last_name, self.user.first_name[:1])
        if self.middle_name:
            name += ' %s.' % self.middle_name[:1]
        return name

class EducationMaterial(models.Model):
    author = models.ForeignKey(User, verbose_name='Автор (преподаватель)')
    subject = models.ForeignKey(Subject, verbose_name='Дисциплина')
    department = models.ForeignKey(Department, verbose_name='Кафедра')
    university = models.ForeignKey(University, verbose_name='ВУЗ')
    name = models.CharField(max_length=255, verbose_name='Название материала')
    description = models.TextField(verbose_name='Описание', blank=True)
    last_update_dt = models.DateTimeField(verbose_name='Дата последнего изменения', auto_now=True)
    create_dt = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    pub = models.BooleanField(verbose_name='Опубликовать', default=True)


    class Meta:
        verbose_name = 'Учебный материал'
        verbose_name_plural = 'Учебные материалы'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return '/material/university/%s/department/%s/subject/%s/lector/%s/%s/' % (self.university.id, self.department.id, self.subject.id, self.author.id, self.pk)

class EducationFiles(models.Model):
    material = models.ForeignKey(EducationMaterial, verbose_name='Материал')
    name = models.CharField(max_length=255, verbose_name='Раздел курса')
    file = models.FileField(upload_to='materials', verbose_name='Файл')
    upload_dt = models.DateField(verbose_name='Дата загрузки', auto_now_add=True)

    def __unicode__(self):
        return '%s - %s' % (self.material.name, self.name)

    def get_absolute_url(self):
        return '%s%s' % (settings.MEDIA_URL, self.file)

# These two auto-delete files from filesystem when they are unneeded:
@receiver(models.signals.post_delete, sender=EducationFiles)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)

@receiver(models.signals.pre_save, sender=EducationFiles)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `MediaFile` object is changed.
    """
    if not instance.pk:
        return False

    try:
        old_file = EducationFiles.objects.get(pk=instance.pk).file
    except EducationFiles.DoesNotExist:
        return False


class EducationTest(models.Model):
    author = models.ForeignKey(User, verbose_name='Автор (преподаватель)')
    subject = models.ForeignKey(Subject, verbose_name='Дисциплина')
    department = models.ForeignKey(Department, verbose_name='Кафедра')
    university = models.ForeignKey(University, verbose_name='ВУЗ')
    name = models.CharField(max_length=255, verbose_name='Название теста')
    description = models.TextField(verbose_name='Описание', blank=True)
    material = models.ForeignKey(EducationMaterial, verbose_name='Учебный материал', on_delete=models.SET_NULL, null=True, blank=True)
    last_update_dt = models.DateTimeField(verbose_name='Дата последнего изменения', auto_now=True)
    create_dt = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    pub = models.ManyToManyField(UserProfile, verbose_name='Опубликовать')
    level_up = models.IntegerField(verbose_name='Количество правильныйх ответов для повышения уровня сложности вопроса', default=0)
    level_down = models.IntegerField(verbose_name='Количество неправильных ответов для понижения уровня сложности вопроса', default=0)

    # градация оценки
    fail = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Меньше', help_text='Оценка 2')
    not_fail = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Меньше', help_text='Оценка 3')
    good = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Меньше', help_text='Оценка 4')
    # excellent = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Больше', help_text='Оценка 5')
    # меньше 33,33% - это оценка 2
    # от 33,33% до 44,44% - это оценка 3
    # от 44,44% до 66,66% - это оценка 4
    # и все что выше 66,66% это пять

    def admin_questions(self):
        return '<a href="/admin/organization/testquestion/?test__id__exact=%s">Вопросы</a>' % self.id
    admin_questions.allow_tags = True
    admin_questions.short_description = u'Вопросы'

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return '/test/university/%s/department/%s/subject/%s/lector/%s/%s/' % (self.university.id, self.department.id, self.subject.id, self.author.id, self.pk)

    def get_questions(self):
        return TestQuestion.objects.filter(test=self)

    def get_simple_questions(self):
        return self.get_questions().filter(complexity=1)

    def get_normal_questions(self):
        return self.get_questions().filter(complexity=2)

    def get_difficult_questions(self):
        return self.get_questions().filter(complexity=3)



COMPLEXITY_CHOICES = ((1, 'Простой'),(2, 'Средний'),(3, 'Сложный'))

class TestQuestion(models.Model):
    test = models.ForeignKey(EducationTest, verbose_name='Тест')
    number = models.IntegerField(verbose_name='Номер вопроса', default=0)
    question = RichTextField(verbose_name='Вопрос')
    description = models.TextField(verbose_name='Описание', blank=True)
    material_part = models.ForeignKey(EducationFiles, verbose_name='Раздел учебного материала', on_delete=models.SET_NULL, null=True, blank=True)
    last_update_dt = models.DateTimeField(verbose_name='Дата последнего изменения', auto_now=True)
    create_dt = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    pub = models.BooleanField(verbose_name='Опубликовать', default=False)
    time = models.IntegerField(verbose_name='Время ответа на вопрос (мин)', default=1)
    complexity = models.IntegerField(verbose_name='Сложность вопроса', choices=COMPLEXITY_CHOICES, default=COMPLEXITY_CHOICES[0][0])

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

    def __unicode__(self):
        return self.question

    def get_absolute_url(self):
        return '/test/%s/question/%s/' % (self.test.id, self.pk)

class QuestionAnswer(models.Model):
    question = models.ForeignKey(TestQuestion, verbose_name='Вопрос')
    answer = models.CharField(max_length=255, verbose_name='Вариант ответа')
    correct = models.BooleanField(default=False, verbose_name='Правильный ответ')

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

    def __unicode__(self):
        return self.answer


class TestSessions(models.Model):
    session_id = models.CharField(max_length=255, verbose_name='Session ID')
    user = models.ForeignKey(User, verbose_name='Пользователь')
    test = models.ForeignKey(EducationTest, verbose_name='Тест')
    question = models.ForeignKey(TestQuestion, verbose_name='Вопрос')

templates/organization/inc/add_education_material_file_form.html
<form action="" method="post" id="add_education_material" role="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group {% if field.errors %} has-error {% endif %}">
        <label for="{{ field.html_name }}">{{ field.label }}</label>
        {{ field }}
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="help-block">{{ error|escape }}</div>
            {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <div class="form-group">
        <button class="btn btn-success btn-block" type="submit"><i class="fa fa-cloud-upload fa-fw"></i> Загрузить</button>
    </div>
</form>

templates/organization/inc/add_education_material_form.html
<form action="{% url 'add_education_material' %}" method="post" id="add_education_material" role="form">
    {% csrf_token %}
    <input type="hidden" name="material_id" value="{{ page.id }}">
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.html_name }}">{{ field.label }}</label>
        {{ field }}
        <div class="help-block"></div>
    </div>
    {% endfor %}
    <div class="form-group">
        <button class="btn btn-md btn-block btn-success" type="submit">
            {% if page.id %}
                <i class="fa fa-save fa-fw"></i> Сохранить
            {% else %}
                <i class="fa fa-plus fa-fw"></i> Создать
            {% endif %}
        </button>
    </div>
</form>

templates/organization/inc/add_education_test_form.html
<form action="{% url 'add_education_test' %}" method="post" id="add_education_test" role="form">
    {% csrf_token %}
    <input type="hidden" name="test_id" value="{{ page.id }}">
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.html_name }}">{{ field.label }}</label>
        {{ field }}
        <div class="help-block"></div>
    </div>
    {% endfor %}
    <div class="form-group">
        <button class="btn btn-md btn-block btn-success" type="submit">
            {% if page.id %}
                <i class="fa fa-save fa-fw"></i> Сохранить
            {% else %}
                <i class="fa fa-plus fa-fw"></i> Создать
            {% endif %}
        </button>
    </div>
</form>

templates/organization/inc/add_test_question_form.html
{{ form.media }}
{#<form action="{% url 'add_test_question' %}" method="post" id="add_test_question_form" role="form" enctype="multipart/form-data">#}
<form action="" method="post" id="add_test_question_form" role="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group {% if field.errors %} has-error {% endif %}">
        <label for="{{ field.html_name }}">{{ field.label }}</label>
        {{ field }}
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="help-block">{{ error|escape }}</div>
            {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <div class="form-group">
        <button class="btn btn-success btn-block" type="submit" form="add_test_question_form"><i class="fa fa-save fa-fw"></i> Сохранить</button>
    </div>
</form>

templates/organization/inc/answers_form.html
<div class="question" data-time="{{ question.time }}">
    <h4 data-complexity="{{ question.complexity }}]">Вопрос</h4>
    {{ question.question|safe }}
</div>
<input type="hidden" name="question_id" value="{{ question.id }}">
<hr/>
<h4>Варианты ответов</h4>
{% for a in answers %}
    <div class="radio">
        <label>
            <input type="radio" name="answer_id" id="optionsRadios_{{ a.id }}" value="{{ a.id }}">
            {{ a.answer|safe }}
{#            {% if a.correct %} [правильный] {% endif %}#}
        </label>
    </div>
{% endfor %}

templates/organization/inc/navigation.html
<nav class="navbar navbar-white" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-white-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">АСДО</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-white-collapse">
            <ul class="nav navbar-nav navbar-left">
                <li {% if test %} class="active" {% endif %}><a href="/test/"><i class="fa fa-list-alt fa-fw"></i> Тесты</a></li>
                <li {% if material %} class="active" {% endif %}><a href="/material/"><i class="fa fa-book fa-fw"></i> Учебные материалы</a></li>
                <li {% if stat %} class="active" {% endif %}><a href="/stat/"><i class="fa fa-tasks fa-fw"></i> Статистика</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        {% if user_group.pk == 1 %}
                            <i class="fa fa-graduation-cap fa-fw"></i>
                        {% elif user_group.pk == 2 %}
                            <i class="fa fa-university fa-fw"></i>
                        {% else %}
                            <i class="fa fa-life-ring fa-fw"></i>
                        {% endif %}
                        {{ user.profile.get_full_name }} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><span>Статус: {% for group in user.groups.all %}{{ group.name }}{% endfor %}</span></li>
                        <li><span>ВУЗ: {{ user.profile.university }}</span></li>
                        <li><span>Кафедра: {{ user.profile.department }}</span></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'logout' %}">Выход</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>



{% if not home %}
<nav class="navbar navbar-gray" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-gray-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-gray-collapse">
            <ul class="nav navbar-nav">

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Университет: <strong>{{ university.name }}</strong></a>
                    {% if university_list %}
                        <ul class="dropdown-menu" role="menu" id="university_list">
                            {% for item in university_list %}
                                <li><a href="
                                    {% if materials_page %}
                                        {% url 'material_university' item.pk %}
                                    {% elif test_page %}
                                        {% url 'test_university' item.pk %}
                                    {% else %}
                                        {% url 'stat_university' item.pk %}
                                    {% endif %}
                                    ">{{ item.name }}</a></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
                <li><a><i class="fa fa-angle-right"></i></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Кафедра: <strong>{{ department.name }}</strong></a>
                    {% if department_list %}
                        <ul class="dropdown-menu" role="menu" id="department_list">
                            {% for item in department_list %}
                                <li><a href="
                                    {% if materials_page %}
                                        {% url 'material_department' university.id item.pk %}
                                    {% elif test_page %}
                                        {% url 'test_department' university.id item.pk %}
                                    {% else %}
                                        {% url 'stat_department' university.id item.pk %}
                                    {% endif %}
                                    ">{{ item.full_name }}</a></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
                <li><a><i class="fa fa-angle-right"></i></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Дисциплина: <strong>{{ subject.name }}</strong></a>
                    {% if subject_list %}
                        <ul class="dropdown-menu" role="menu" id="subject_list">
                            {% for item in subject_list %}
                                <li><a href="
                                    {% if materials_page %}
                                        {% url 'material_subject' university.id department.id item.pk %}
                                    {% elif test_page %}
                                        {% url 'test_subject' university.id department.id item.pk %}
                                    {% else %}
                                        {% url 'stat_subject' university.id department.id item.pk %}
                                    {% endif %}
                                    ">{{ item.full_name }}</a></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
                {% if user_group.pk == 1 %}
                    <li><a><i class="fa fa-angle-right"></i></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Преподаватель: <strong>{{ lector.profile.get_name }}</strong></a>
                        {% if lector_list %}
                            <ul class="dropdown-menu" role="menu" id="lector_list">
                                {% for item in lector_list %}
                                    <li><a href="
                                        {% if materials_page %}
                                            {% url 'material_lector' university.id department.id subject.id item.pk %}
                                        {% elif test_page %}
                                            {% url 'test_lector' university.id department.id subject.id item.pk %}
                                        {% else %}
                                            {% url 'stat_lector' university.id department.id subject.id item.pk %}
                                        {% endif %}
                                        ">{{ item.profile.get_full_name }}</a></li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </li>
                {% endif %}

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{% endif %}